(load "~/quicklisp/setup.lisp")
(ql:quickload :cl-quickcheck)
(ql:quickload :defenum)

(let ((*random-state* (make-random-state t))
      (*print-length* 6)
      (*load-verbose* t))

  (shadow 'cl-quickcheck:report '#:cl-user)
  (shadow 'defenum:enum         '#:cl-user)
  (use-package :cl-quickcheck)
  (use-package :defenum)

  (load "test/point.lisp")
  (load "test/box.lisp")
  (load "test/geo.lisp")
  (load "test/world.lisp")
  (load "test/storey.lisp")
  (load "test/room.lisp")
  (load "test/rendering.lisp")
  )
